name: 'Salesforce CI/CD Pipeline'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    name: 'Validate Salesforce Code'
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        
      # Option 1: If sf_ci_shared is a separate repository, use this format:
      # - name: 'Setup Salesforce Environment'
      #   uses: gambe94/sf_ci_shared/.github/actions/setup-sf-env@main
      #   with:
      #     node-version: '18'
      #     sf-cli-version: 'latest'
      #     cache-dependencies: 'true'
      #     install-dependencies: 'true'
      
      # Using the separate sf_ci_shared repository:
      - name: 'Setup Salesforce Environment'
        uses: gambe94/sf_ci_shared/.github/actions/setup-sf-env@main
        with:
          node-version: '18'
          sf-cli-version: 'latest'
          cache-dependencies: 'true'
          install-dependencies: 'true'
          working-directory: '.'
          plugins: '@salesforce/sfdx-scanner,@salesforce/plugin-packaging,sfdx-git-delta'
      
      - name: 'Display environment info'
        run: |
          echo "Node.js version: ${{ steps.setup-sf.outputs.node-version }}"
          echo "SF CLI version: ${{ steps.setup-sf.outputs.sf-cli-version }}"
          echo "Plugins installed: ${{ steps.setup-sf.outputs.plugins-installed }}"
          echo "Cache hit: ${{ steps.setup-sf.outputs.cache-hit }}"
      
      - name: 'Run ESLint'
        run: echo "Running ESLint...".
        
      - name: 'Run Jest Tests'
        run: echo "Running Jest Tests...".
        
